version: '2'
services:
  angular: 
    build: .
    volumes:
      -./src:/app/src
    ports:
      - 4200:4200
  
  api:
    image: container-docker
    ports: 
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=fulbo
      - DB_PASSWORD=del0al9
      - DB_NAME=db_fulbo
    

  database:
    image: container-docker
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    enviroment:
      - POSTGRES_USER=fulbo
      - POSTGRES_PASSWORD=del0al9
      - POSTGRES_DB=db_fulbo
      - PG_DATA=/var/lib/postgresql/data/pgdata

volumes:
  pg_data:  